const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('menuAPI', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getDisplays: () => ipcRenderer.invoke('get-displays'),
  getHistory: () => ipcRenderer.invoke('get-history'),
  updateSettings: (s) => ipcRenderer.send('update-settings', s),
  testMascot: () => ipcRenderer.send('test-mascot'),
  clearHistory: () => ipcRenderer.send('clear-history'),
  closeMenu: () => ipcRenderer.send('close-menu'),
  quitApp: () => ipcRenderer.send('quit-app'),
  claudeStatus: () => ipcRenderer.invoke('claude-status'),
  claudeConnect: () => ipcRenderer.invoke('claude-connect'),
  claudeDisconnect: () => ipcRenderer.invoke('claude-disconnect'),
  cursorStatus: () => ipcRenderer.invoke('cursor-status'),
  cursorConnect: () => ipcRenderer.invoke('cursor-connect'),
  cursorDisconnect: () => ipcRenderer.invoke('cursor-disconnect'),
  codexStatus: () => ipcRenderer.invoke('codex-status'),
  codexConnect: () => ipcRenderer.invoke('codex-connect'),
  codexDisconnect: () => ipcRenderer.invoke('codex-disconnect'),
  onUpdateState: (cb) => ipcRenderer.on('update-state', (_, d) => cb(d)),
  onNewNotification: (cb) => ipcRenderer.on('new-notification', (_, d) => cb(d)),
  toggleDnd: () => ipcRenderer.send('toggle-dnd'),
  onDndChanged: (cb) => ipcRenderer.on('dnd-changed', (_, dnd) => cb(dnd)),
  onApplyTheme: (cb) => ipcRenderer.on('apply-theme', (_, d) => cb(d)),
  applyTheme: (name) => ipcRenderer.send('apply-theme', name),
  getThemes: () => ipcRenderer.invoke('get-themes'),
  changeSound: (name) => ipcRenderer.send('change-sound', name),
  getSounds: () => ipcRenderer.invoke('get-sounds'),
  getLanguage: () => ipcRenderer.invoke('get-language'),
  changeLanguage: (lang) => ipcRenderer.send('change-language', lang),
  onLanguageChanged: (cb) => ipcRenderer.on('language-changed', (_, lang) => cb(lang)),
  getApprovalMode: () => ipcRenderer.invoke('get-approval-mode'),
  changeApprovalMode: (mode) => ipcRenderer.send('change-approval-mode', mode)
});
